browser:
  name: chrome
  headless: false
  implicit_wait: 10
  explicit_wait: 20

environment:
  local:
    base_url: http://localhost:3000
  staging:
    base_url: https://staging.example.com
  production:
    base_url: https://example.com

reporting:
  html_report: true
  allure_report: true
  screenshot_on_failure: true
  log_level: INFO

test_data:
  default_user:
    username: test_user
    password: test_pass 